import type { Metadata } from 'next';
import { Nunito_Sans, Sora } from 'next/font/google';
import './globals.css';


const nunito = Nunito_Sans({
  variable: '--font-nunito-sans',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
});
// TODO: change font Sora to Inter
const sora = Sora({
  variable: '--font-sora',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
// TODO: move About to the mainPage
import About from '@/components/About/About';
import QueryProvider from './providers/QueryProvider';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${sora.variable}`}>
        <QueryProvider>
          <Header />
          <About />
          <main>{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
